name: Next CI Pipeline

on:
  pull_request:
    types: [opened, reopened, synchronize]
  push: 
    branches: [master, develop]
permissions:
  contents: read
jobs:
  config:
    uses: odsquiz-io/odsquiz-workflows/.github/workflows/next-ci-pipeline.yaml@main
    